name: Terraform

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest

    container:
      image: hashicorp/terraform:1.0.10

    steps:
      - uses: actions/checkout@v1
      - run: terraform fmt -check -recursive .
